### ISSUE TITLE
Main branch is broken due to SDK changes. Use cdkUpgrade branch.

### ISSUE THREAD

**Issue by ibliskavka** [aws-samples/amazon-chime-sma-call-forwarding#4]
Dropping this in case someone else bumps into this issue.

Chime SDK changes broke the main branch. Use the `cdkUpgrade` branch instead.

Update:
- `boto3.client("chime"` to `boto3.client("chime-sdk-voice"` in src/resources/callControl/index.py
- `yarn && npm run build && npm run deploy`

**Comment by schuettc** [comment]
cdkUpgrade branch has been updated and merged in.  Thanks!

https://github.com/aws-samples/amazon-chime-sma-call-forwarding/commit/eff943a95a4f6c05644afdca9dd53b468a62a03f

**Comment by ibliskavka** [comment]
@schuettc I just saw you merged in the branch, thank you! It took me an hour to figure out the issue.

Please double check [this line](https://github.com/aws-samples/amazon-chime-sma-call-forwarding/blob/8400122ce9f76dd6b6f037e12a476b402fae03bd/src/resources/callControl/index.py#L16)

As-is, you will get an error when you try to assign a number from the UI.

The fix is to use a different client:
`boto3.client("chime-sdk-voice", config=client_config, region_name=os.environ["AWS_REGION"])`
